apiVersion: certmanager.k8s.io/v1alpha2
kind: Certificate
metadata:
  name: example
  namespace: example
spec:
  secretName: example
  dnsNames:
    - example.hostname.com
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer