apiVersion: v1
kind: Namespace
metadata:
  name:  prometheus

---

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  releaseName: prometheus
  chart:
    git: ssh://git@github.com/helm/charts/
    path: stable/prometheus
    ref: master
  values:
    replicaCount: 1