apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    - name: cert-manager
      version: v0.6.7
      repository: https://kubernetes-charts.storage.googleapis.com
