apiVersion: v1
kind: Deployment
metadata:
  name: rx-nest
  namespace: rx-nest
  annotations:
    fluxcd.io/automated: 'true'

spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: rx-nest
        image: turao/nestjs-microservices
