# Chart
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  releaseName: sealed-secrets
  chart:
    name: sealed-secrets
    version: 1.6.1
    repository: https://kubernetes-charts.storage.googleapis.com
