apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
  metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://kubernetes-charts.storage.googleapis.com
    chart: prometheus-operator
    targetRevision: 8.12.12

    helm:
      values: |-
        {{ .Files.Get "config/prometheus-operator.yaml" | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring